//solution by using synchronised method which will pause the below thread until thread1 run completely 
class WithdrawThread extends Thread{
   static int totalbalance=1000;
int amount;
public WithdrawThread(int amount){
    this.amount=amount;
}
    public void run(){
        synchronized(WithdrawThread.class){
if(totalbalance>=amount){
            System.out.println("amount withdraw"+amount);
            try{
                Thread.sleep(2000);
            }catch(InterruptedException e){
                //TODO autogenerated catch block
                //e.printStackTrace();
            }
            totalbalance-=amount;
            System.out.println(totalbalance);
        }
        else{
                System.out.println("insufficient balance");
        }
        }
        
    }
}

class Hello{
    public static void main(String[] args) {
        WithdrawThread t1=new WithdrawThread(800);
        WithdrawThread t2=new WithdrawThread(500);// thread will run one after other after one thread run completed
        t1.start();
        t2.start();
    }
}
//amount withdraw 800
//200
//insufficient balance