 //problem in multithread cause both will run together and withdraw the amount
 //solution will be to complete one thread completely and then run the other
 class WithdrawThread extends Thread{
   static int totalbalance=1000;
int amount;
public WithdrawThread(int amount){
    this.amount=amount;
}
    public void run(){
        if(totalbalance>=amount){
            System.out.println("amount withdraw"+amount);
            try{
                Thread.sleep(2000);
            }catch(InterruptedException e){
                //TODO autogenerated catch block
                //e.printStackTrace();
            }
            totalbalance-=amount;
            System.out.println(totalbalance);
        }
        else{
                System.out.println("insufficient balance");
        }
    }
}

class Hello{
    public static void main(String[] args) {
        WithdrawThread t1=new WithdrawThread(800);
        WithdrawThread t2=new WithdrawThread(500);//both thread will run together simultaneously independant of each other
        t1.start();
        t2.start();
    }
}
//amount withdraw 800
//amount withdraw 500
//200
//-300